package main

import "errors"

// The cases of the runs that write the registry, and of the foreign writer that undoes the write or
// tears the read around it.

// foreignRegistry is what another tool leaves when it regenerates the registry whole.
const foreignRegistry = "# Skill Registry\n\nregenerated by another tool\n"

// clobber is a foreign writer that replaces the registry with the text.
func clobber(text string) func(*propagateWorld) {
	return func(w *propagateWorld) { w.files[registryFile] = text }
}

func propagateWriteCases() []propagateCase {
	return []propagateCase{
		{"propagate-loop-written", func(w *propagateWorld) {
			w.withContract()
			w.files[registryFile] = goldenRegistry
			w.propagate("the block is inserted and read back", propagateArgs...)
			w.propagate("the same run again is silent and writes nothing", propagateArgs...)
		}},
		{"propagate-loop-written-embedded", func(w *propagateWorld) {
			w.files[registryFile] = goldenRegistry
			args := []string{"--registry", registryFile, "--embedded-contract", "anti-generic-design"}
			w.propagate("the embedded contract is inserted under its own row", args...)
			w.propagate("an explicit path for the row", append(args, "--contract-path", "custom/anti-generic-design.md")...)
		}},
		{"propagate-loop-arguments", func(w *propagateWorld) {
			w.withContract()
			w.files[registryFile] = goldenRegistry
			w.propagate("the last --registry wins and is cleaned",
				"--registry", "/virtual/elsewhere.md", "--contract-file", contractFile, "--registry", "/virtual/project/../project/.atl/skill-registry.md")
			w.propagate("a flag as the last argument has no value", append(append([]string{}, propagateArgs...), "--contract-path")...)
		}},
		{"propagate-loop-clobbered-once", func(w *propagateWorld) {
			w.withContract()
			w.files[registryFile] = goldenRegistry
			w.afterWrite[1] = clobber(foreignRegistry)
			w.propagate("a foreign writer wins the first write: the second attempt writes on top", propagateArgs...)
		}},
		{"propagate-loop-clobbered-every-time", func(w *propagateWorld) {
			w.withContract()
			w.files[registryFile] = goldenRegistry
			for n := 1; n <= 3; n++ {
				w.afterWrite[n] = clobber(foreignRegistry)
			}
			w.propagate("a foreign writer wins every write: the run fails", propagateArgs...)
		}},
		{"propagate-loop-clobbered-into-the-same-block", func(w *propagateWorld) {
			w.withContract()
			w.files[registryFile] = goldenRegistry
			w.afterWrite[1] = func(w *propagateWorld) { w.files[registryFile] += "\nadded by another tool\n" }
			w.propagate("the foreign writer keeps the block: the second attempt finds it correct and is silent", propagateArgs...)
		}},
		{"propagate-loop-write-fails-after-a-clobber", func(w *propagateWorld) {
			w.withContract()
			w.files[registryFile] = goldenRegistry
			w.afterWrite[1] = clobber(foreignRegistry)
			w.writeErrors[2] = errors.New("no space left on device")
			w.propagate("the first write is lost, the second fails: forwarded", propagateArgs...)
		}},
	}
}
