package main

// The usage text of the engine command: one block per subcommand, printed on stderr when the command line is not understood.

import (
	"fmt"
	"io"
)

// usage writes the usage text to w.
func usage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  engine propagate --registry <path> (--contract-file <path> [--contract-path <str>] | --embedded-contract <name>) [--require-registry]")
	fmt.Fprintln(w, "  engine gate-task (--contract-file <path> | --embedded-contract <name>) [--contract-path <str>]")
	fmt.Fprintln(w, "  engine merge-settings --settings <path> --hook-command <binary-path>")
	fmt.Fprintln(w, "  engine uninstall-hooks --settings <path> --hook-command <binary-path>")
	fmt.Fprintln(w, "  engine status")
	fmt.Fprintln(w, "  engine prespec <verb>  (verbs: rank, lint, readiness, brief)")
	fmt.Fprintln(w, "  engine runtime <action> [--target claude|opencode|codex|pi|all] [--config-root <path>]")
	fmt.Fprintln(w, "                          [--component runtime-parity|longterm-mem] [--state-dir <path>]")
	fmt.Fprintln(w, "    action: status | install | update | uninstall")
	fmt.Fprintln(w, "    --target: opencode (default), claude, codex, pi, or all (--component runtime-parity only)")
	fmt.Fprintln(w, "    --component: runtime-parity (default, the --target adapters above), or longterm-mem")
	fmt.Fprintln(w, "      (a single component spanning claude+opencode+codex; no update/rollback action)")
	fmt.Fprintln(w, "    --state-dir: registration.json directory for --component longterm-mem (default ~/.labdrian-overlay)")
	fmt.Fprintln(w, "  engine runtime capabilities [--target claude|codex|pi|opencode|all]")
	fmt.Fprintln(w, "    read-only: prints, as JSON, what each runtime adapter declares it supports (default --target all);")
	fmt.Fprintln(w, "    every supported or partial claim names the tests that prove it, every partial or unsupported claim")
	fmt.Fprintln(w, "    states its limit, and untested appears only for a runtime that cannot be exercised on this machine")
	fmt.Fprintln(w, "    reads no configuration, HOME, or file; exit 0 success, 2 unknown --target value, 1 usage error including an unknown flag")
	fmt.Fprintln(w, "  engine runtime probe [--target claude|codex|pi|all]")
	fmt.Fprintln(w, "    read-only, stat only: prints, as JSON, whether each selected runtime's credentials file is present (default")
	fmt.Fprintln(w, "    --target all) and whether the Engram database, the longterm-mem registration record, and the gentle-ai binary")
	fmt.Fprintln(w, "    on PATH are present, from the real HOME and PATH; it never opens or reads a file and never runs a program, so")
	fmt.Fprintln(w, "    a present credentials file does not prove the runtime is authenticated; exit 0 success, 2 unknown --target value,")
	fmt.Fprintln(w, "    1 usage error including an unknown flag")
	fmt.Fprintln(w, "  OVERLAY_DIR=<repo-root> gentle-ai-overlay gadu-generate [--check]")
	fmt.Fprintln(w, "  engine pipkg build|check --overlay-root <path> --registry <path> --dest-dir <path>")
	fmt.Fprintln(w, "    build: writes the labdrian-pi package tree to --dest-dir")
	fmt.Fprintln(w, "    check: reports drift between --dest-dir and the current manifest; exit 1 on drift")
	fmt.Fprintln(w, "  engine skills <verb>   (verbs: list, status, validate, install, adopt, add, remove, sync-manifest, lint, approve, project-register, project-revise, project-status, project-retire)")
	fmt.Fprintln(w, "    list          [--registry <path>]                                                      print sorted registry entries")
	fmt.Fprintln(w, "    status        [--registry <path>]                                                      print count summary (total/core/custom)")
	fmt.Fprintln(w, "    validate      [--registry <path>] [--manifest <path>] --source-root <path>              cross-check registry vs manifest and skills/ on disk; exit 1 on divergence")
	fmt.Fprintln(w, "    install       [--registry <path>] [--source-root <path>] [--project-id <id>]           install project-scoped skills into <cwd>/.claude/skills/ and <cwd>/.agents/skills/, replacing only what it installed and left unmodified")
	fmt.Fprintln(w, "                  install records each file it writes (with its SHA-256) in the project lock. It refuses, naming the path, a hand-edited file or a directory it did not install,")
	fmt.Fprintln(w, "                  reports every refusal, and then writes nothing for any skill. A second install with no source change prints \"unchanged: <id>\" and writes nothing.")
	fmt.Fprintln(w, "    adopt         [--registry <path>] [--source-root <path>] [--project-id <id>]           record skill directories already in the project as installed, only when they are exactly the current source;")
	fmt.Fprintln(w, "                  nothing is adopted silently: a directory stays foreign to install until skills adopt records it. adopt writes the project lock and no skill file")
	fmt.Fprintln(w, "    add           <id> [--registry <path>] [--manifest <path>] [--source-root <path>] [--repo <url>] [--ref <sha>]  register a skill")
	fmt.Fprintln(w, "    remove        <id> [--registry <path>] [--manifest <path>]                             unregister a skill from registry and manifest")
	fmt.Fprintln(w, "    sync-manifest [--registry <path>] [--manifest <path>]                                  regenerate */SKILL.md rows from registry")
	fmt.Fprintln(w, "    lint          <path> | --rules                                                         lint a SKILL.md file, or print the rule table; exit 1 on any hard error")
	fmt.Fprintln(w, "    approve       --id <id> --approver <label> --source-root <path>                        record a human approval of skills/<id>/SKILL.md, bound to the digest of its exact bytes")
	fmt.Fprintln(w, "                  a skill that fails the hard lint is refused, except a baseline skill (a grandfathered global skill, which predates the lint budget and will be rewritten in a later feature):")
	fmt.Fprintln(w, "                  for those, a size or description finding is printed as a \"warning:\" line on stderr, the approval is still recorded, and the exit is 0;")
	fmt.Fprintln(w, "                  any other hard finding, such as a missing front matter, refuses a baseline skill too")
	fmt.Fprintln(w, "    project-register --project-root <abs> --candidate <key> [--dry-run] [--registry <path>] <draft-file>")
	fmt.Fprintln(w, "                                                                                           register a project-tier procedural skill; --dry-run prints the plan and writes nothing")
	fmt.Fprintln(w, "    project-revise   --project-root <abs> --candidate <key> [--dry-run] [--registry <path>] <draft-file>")
	fmt.Fprintln(w, "                                                                                           revise an agent-owned project skill; --dry-run prints the plan and writes nothing")
	fmt.Fprintln(w, "    project-status   --project-root <abs> [--registry <path>] [<id>]")
	fmt.Fprintln(w, "                                                                                           report project-tier ownership and global supersession")
	fmt.Fprintln(w, "    project-retire   --project-root <abs> [--dry-run] [--reason <reason>] [--absorbed-into <id>] [--registry <path>] <id>")
	fmt.Fprintln(w, "                                                                                           retire an agent-owned project skill; --dry-run prints the removal plan")
	fmt.Fprintln(w, "    locking: add, remove, sync-manifest and approve hold an exclusive lock, and validate and install a shared one, on .skills.registry.yaml.lock beside the registry")
	fmt.Fprintln(w, "    (created by the first write, never removed, git-ignored; shared holders never create it). A lock taken for 2 seconds means another skills command is in progress:")
	fmt.Fprintln(w, "    the verb changes nothing and reports it with exit 2 (retry); exit 1 is unchanged (the verb ran or was refused, or the lock could not be created)")
	fmt.Fprintln(w, "    project lock: project-register, project-revise, project-retire, install and adopt also take an exclusive lock on the project root directory itself (--project-root, or")
	fmt.Fprintln(w, "    the working directory for install and adopt), so no file is created in the project; a busy one is exit 2 too, and a filesystem that cannot lock a directory refuses the verb (exit 1).")
	fmt.Fprintln(w, "    A verb that holds both takes the overlay lock first, then the project lock, so install and adopt can wait up to twice the lock bound (2 seconds each) when both are busy;")
	fmt.Fprintln(w, "    project-status takes a shared lock on the project. A writer refuses, with nothing locked, when the registry it would lock does not exist")
	fmt.Fprintln(w, "  engine skills guard-hook")
	fmt.Fprintln(w, "    internal Claude Code PreToolUse hook command (install-hooks installs it; on an existing install, re-run install-hooks and restart Claude Code to load it):")
	fmt.Fprintln(w, "    reads the hook JSON on stdin and denies the agent running 'skills approve' (approval is a human step) or writing a skill's .approval.json record with")
	fmt.Fprintln(w, "    Write, Edit, MultiEdit, or NotebookEdit. A denial is {\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",")
	fmt.Fprintln(w, "    \"permissionDecisionReason\":...}} with exit 0; an allow prints nothing. A speed bump, not a security boundary: it matches the command text and the file name,")
	fmt.Fprintln(w, "    so it can be bypassed and can deny text that only spells the invocation. It never blocks on an error (unusable input is an allow): exit 0 always, 1 usage error")
	fmt.Fprintln(w, "  engine sync-trigger --event session-end|archive --cwd <path> [--state-dir <path>]")
	fmt.Fprintln(w, "    always exits 0 to its caller; detaches a bounded longterm-mem sync and logs its outcome")
	fmt.Fprintln(w, "  engine review-receipt capture --cwd <repo> [--change <name>]")
	fmt.Fprintln(w, "    persists every surviving approved review receipt to openspec/changes/<change>/review-receipts/")
	fmt.Fprintln(w, "    --change resolves ambiguity when more than one active change exists; omit it to auto-detect")
	fmt.Fprintln(w, "  engine review-receipt hook --cwd <repo>")
	fmt.Fprintln(w, "    fail-closed PreToolUse Bash hook: reads tool_input JSON from stdin, captures before")
	fmt.Fprintln(w, "    'gentle-ai review acknowledge-approved', denies (exit 2) on ambiguity or capture failure")
	fmt.Fprintln(w, "  engine shaper assess --root <abs> --handoff <rel> --goal <rel> [--view]")
	fmt.Fprintln(w, "    read-only readiness assessment; exit 0 ready, 3 draft, 2 invalid, 1 usage or internal error")
	fmt.Fprintln(w, "    --view prints exactly the rendered clearance view bytes the Pi dialog displays")
	fmt.Fprintln(w, "  engine shaper clearance record --root <abs> --handoff <rel> --goal <rel> --stdin")
	fmt.Fprintln(w, "    stores a human clearance decision read only from stdin after re-deriving and checking its binding")
	fmt.Fprintln(w, "    not a signature: any process running as the same OS user, including any installed Pi extension, can forge one")
	fmt.Fprintln(w, "  engine shaper guard-hook")
	fmt.Fprintln(w, "    Claude Code PreToolUse deny guard for clearance recording and the clearance store (exit 2 denies; a speed bump)")
	fmt.Fprintln(w, "  engine memory plan --profile <name> [--goal <path>] [--goal-directive <path>] [--handoff-directive <path>]")
	fmt.Fprintln(w, "    read-only: resolves a workflow profile's default memory directive, narrows it with an optional")
	fmt.Fprintln(w, "    Goal-supplied then handoff-supplied directive, and prints the resulting query plan as JSON")
	fmt.Fprintln(w, "    exit 0 plan resolved, 2 refused/invalid input, 1 usage or output error; it never queries or writes memory")
	fmt.Fprintln(w, "  engine workflow create --project <id> --workflow <id> --goal <path> --profile <name> [--role-chain <id>]")
	fmt.Fprintln(w, "  engine workflow start|pause|resume|status --project <id> --workflow <id>")
	fmt.Fprintln(w, "  engine workflow stage  --project <id> --workflow <id> --stage <name>")
	fmt.Fprintln(w, "  engine workflow verify --project <id> --workflow <id> --goal <path>")
	fmt.Fprintln(w, "  engine workflow close  --project <id> --workflow <id> --outcome completed|abandoned [--reason <text>]")
	fmt.Fprintln(w, "    Phase 6 standalone workflow lifecycle: local bookkeeping under $XDG_STATE_HOME/labdrian/workflows/;")
	fmt.Fprintln(w, "    no verb requires Gentle AI, gentle-pi, a runtime, memory, or auth (an unavailable dependency is")
	fmt.Fprintln(w, "    recorded on the event, and a dependency is recorded available only when its file or binary is seen by stat,")
	fmt.Fprintln(w, "    never opened, run, or trusted). --goal is re-read from disk at both create and verify;")
	fmt.Fprintln(w, "    no path is ever persisted. exit 0 success, 2 refused/invalid (illegal transition, verify failure,")
	fmt.Fprintln(w, "    non-owned state), 1 usage error")
	fmt.Fprintln(w, "  engine workflow bind --project <id> --workflow <id>")
	fmt.Fprintln(w, "  engine workflow unbind")
	fmt.Fprintln(w, "  engine workflow binding")
	fmt.Fprintln(w, "    Phase 7 session binding: records which workflow the git repository containing the working directory")
	fmt.Fprintln(w, "    follows, in $XDG_STATE_HOME/labdrian/bindings/<repo-key>.json. The key is the SHA-256 of the git common directory,")
	fmt.Fprintln(w, "    so every worktree of a repository shares one binding. bind needs an existing, owned, not closed workflow;")
	fmt.Fprintln(w, "    it refuses to replace a binding to a workflow that is still active or whose log cannot be read (unbind first)")
	fmt.Fprintln(w, "    and replaces a stale one (closed, gone, corrupt, or not ours). unbind is idempotent and prints {\"removed\": true|false}. binding is read-only:")
	fmt.Fprintln(w, "    it prints the binding's classification and, when owned, the bound workflow's classification and status.")
	fmt.Fprintln(w, "    exit 0 success, 2 refused/invalid (no git repository, a workflow that cannot be bound, a binding file that is not ours")
	fmt.Fprintln(w, "    or cannot be used (foreign, malformed, unavailable), another bind or unbind in progress (busy), a binding another")
	fmt.Fprintln(w, "    process changed meanwhile), 1 usage error")
	fmt.Fprintln(w, "  engine projection hook --event UserPromptSubmit|PreToolUse")
	fmt.Fprintln(w, "    internal Claude Code hook command (install-hooks installs it; on an existing install, re-run install-hooks and restart Claude Code to load it): reads the hook JSON on stdin and prints at most one JSON object.")
	fmt.Fprintln(w, "    UserPromptSubmit prints {\"hookSpecificOutput\":{\"hookEventName\":\"UserPromptSubmit\",\"additionalContext\":...},\"systemMessage\":...}, which puts the")
	fmt.Fprintln(w, "    workflow the repository is bound to (see workflow bind) into the session: id, profile, status, stages, and the memory plan;")
	fmt.Fprintln(w, "    the binding to a closed workflow is removed, and the note says whether it was removed, left alone, or the removal failed.")
	fmt.Fprintln(w, "    PreToolUse gates a tool call against the bound workflow and never writes: it denies Write, Edit, MultiEdit, and NotebookEdit while the")
	fmt.Fprintln(w, "    workflow is paused (never Bash, never a read), and denies a longterm-mem query whose project differs from the memory plan's project")
	fmt.Fprintln(w, "    (every query when the plan has no project); it never touches get, promote, Engram tools, or any write. A denial is")
	fmt.Fprintln(w, "    {\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":...}} with exit 0; an allow prints")
	fmt.Fprintln(w, "    nothing (or only a systemMessage warning) and never permissionDecision allow.")
	fmt.Fprintln(w, "    silent (no output at all) when the repository is not bound, the input is not a usable hook input, or the directory is not in a")
	fmt.Fprintln(w, "    repository; on UserPromptSubmit a bound workflow that cannot be followed, or a binding store that cannot be read, gives one warning and")
	fmt.Fprintln(w, "    nothing is projected (PreToolUse allows quietly). read-only otherwise. exit 0 always (it never blocks a prompt or a tool call), 1 usage error")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Embedded contracts: anti-generic-design")
	fmt.Fprintln(w, "status exit codes: 0 ok, 1 hard failure, 2 degraded")
}
