package app_test

import (
	"errors"
	"strings"
	"testing"

	"github.com/labdrian-ai/labdrian-sdd-overlay/engine/contract"
	"github.com/labdrian-ai/labdrian-sdd-overlay/engine/propagator"
	"github.com/labdrian-ai/labdrian-sdd-overlay/engine/propagator/app"
)

const registryPath = "/project/.atl/skill-registry.md"

const contractText = "---\napplies_to_phases: [sdd-tasks, sdd-apply]\nexcluded_phases: [sdd-propose]\n" +
	"injection_point: \"## Skills to load before work\"\n---\n# A contract\n"

const bareRegistry = "# Skill Registry\n\n### Shared Contracts\n\n| Artifact | Path | Description |\n|---|---|---|\n| other | other.md | Other |\n"

// foreign is what another tool leaves when it regenerates the registry whole.
const foreign = "# Skill Registry\n\nregenerated by another tool\n"

func request(c app.ContractSource) app.Request {
	return app.Request{Registry: registryPath, Contract: c, Config: propagator.Config{ContractPath: "skills/_shared/minimalism-contract.md"}}
}

// scoped is the registry the use case writes for bareRegistry.
func scoped(t *testing.T) string {
	t.Helper()
	doc, err := contract.Parse(contractText)
	if err != nil {
		t.Fatal(err)
	}
	out, changed, err := propagator.Propagate(bareRegistry, propagator.Config{ContractPath: "skills/_shared/minimalism-contract.md"}, doc)
	if err != nil || !changed {
		t.Fatalf("Propagate = %v, %v", changed, err)
	}
	return out
}

// ---- one attempt -------------------------------------------------------------------------

func TestAttemptNamesWhatItFound(t *testing.T) {
	correct := scoped(t)
	for _, c := range []struct {
		name  string
		files map[string]string
		want  app.Outcome
		wrote bool
	}{
		{"no registry", map[string]string{}, app.Absent, false},
		{"an empty registry", map[string]string{registryPath: ""}, app.Empty, false},
		{"a registry of white space", map[string]string{registryPath: " \n\t\n"}, app.Empty, false},
		{"a registry that is already correct", map[string]string{registryPath: correct}, app.Unchanged, false},
		{"a registry that lacks the block", map[string]string{registryPath: bareRegistry}, app.Written, true},
	} {
		store := newFakeStore(c.files)
		got, err := app.New(store).Propagate(request(&fakeContract{text: contractText}))
		if err != nil || got.Outcome != c.want {
			t.Errorf("%s: Propagate = %v, %v, want %v", c.name, got.Outcome, err, c.want)
		}
		if (store.writes == 1) != c.wrote || store.writes > 1 {
			t.Errorf("%s: %d writes, want wrote=%v", c.name, store.writes, c.wrote)
		}
		if c.wrote && (string(got.Written) != correct || store.files[registryPath] != correct) {
			t.Errorf("%s: wrote %q, want %q", c.name, got.Written, correct)
		}
		if !c.wrote && got.Written != nil {
			t.Errorf("%s: Written = %q, want none", c.name, got.Written)
		}
	}
}

func TestOutcomeHasAWordForEachKind(t *testing.T) {
	want := map[app.Outcome]string{app.Absent: "absent", app.Empty: "empty", app.Unchanged: "unchanged", app.Written: "written", app.Outcome(0): "unknown"}
	for outcome, word := range want {
		if outcome.String() != word {
			t.Errorf("Outcome(%d).String() = %q, want %q", int(outcome), outcome.String(), word)
		}
	}
}

func TestAttemptRequiresTheRegistryOnlyWhenAsked(t *testing.T) {
	req := request(&fakeContract{text: contractText})
	req.RequireRegistry = true
	_, err := app.New(newFakeStore(nil)).Propagate(req)
	var required *app.RegistryRequiredError
	if !errors.As(err, &required) || required.Path != registryPath {
		t.Fatalf("Propagate = %v, want a RegistryRequiredError for %s", err, registryPath)
	}
	// An empty registry is not an absent one: it exists, so requiring it is met.
	got, err := app.New(newFakeStore(map[string]string{registryPath: ""})).Propagate(req)
	if err != nil || got.Outcome != app.Empty {
		t.Errorf("Propagate over an empty registry = %v, %v, want Empty", got.Outcome, err)
	}
}

func TestAttemptReadsTheContractBeforeTheRegistry(t *testing.T) {
	store := newFakeStore(map[string]string{registryPath: bareRegistry})
	source := &fakeContract{err: errors.New("permission denied")}
	_, err := app.New(store).Propagate(request(source))
	var failed *app.ContractReadError
	if !errors.As(err, &failed) || !strings.Contains(failed.Error(), "permission denied") {
		t.Fatalf("Propagate = %v, want a ContractReadError saying permission denied", err)
	}
	if len(store.log) != 0 {
		t.Errorf("the registry was reached although the contract could not be read: %q", store.log)
	}
}

func TestAttemptRefusesAContractItCannotParse(t *testing.T) {
	store := newFakeStore(map[string]string{registryPath: bareRegistry})
	_, err := app.New(store).Propagate(request(&fakeContract{text: "no frontmatter"}))
	var parse *app.ContractParseError
	if !errors.As(err, &parse) || parse.Err == nil {
		t.Fatalf("Propagate = %v, want a ContractParseError holding the parser's error", err)
	}
	if len(store.log) != 0 {
		t.Errorf("the registry was reached although the contract did not parse: %q", store.log)
	}
}

func TestAttemptReportsWhatItCouldNotReadOrWrite(t *testing.T) {
	read := newFakeStore(nil)
	read.script = []answer{fails("permission denied")}
	_, err := app.New(read).Propagate(request(&fakeContract{text: contractText}))
	var readErr *app.RegistryReadError
	if !errors.As(err, &readErr) || readErr.Path != registryPath || !strings.Contains(err.Error(), "permission denied") {
		t.Errorf("a registry that cannot be read: %v, want a RegistryReadError for %s", err, registryPath)
	}

	write := newFakeStore(map[string]string{registryPath: bareRegistry})
	write.failOn[1] = errors.New("no space left on device")
	_, err = app.New(write).Propagate(request(&fakeContract{text: contractText}))
	var writeErr *app.RegistryWriteError
	if !errors.As(err, &writeErr) || writeErr.Path != registryPath || !strings.Contains(err.Error(), "no space left on device") {
		t.Errorf("a registry that cannot be written: %v, want a RegistryWriteError for %s", err, registryPath)
	}
}

// ---- the loop ----------------------------------------------------------------------------

func TestVerifiedDoesNotRetryWhatIsAlreadyCorrect(t *testing.T) {
	store := newFakeStore(map[string]string{registryPath: scoped(t)})
	source := &fakeContract{text: contractText}
	got, err := app.New(store).PropagateVerified(request(source))
	if err != nil || got != app.Unchanged {
		t.Fatalf("PropagateVerified = %v, %v, want Unchanged", got, err)
	}
	if store.count("read") != 1 || store.writes != 0 || source.reads != 1 {
		t.Errorf("log %q, %d writes, %d contract reads: want one read, no write", store.log, store.writes, source.reads)
	}
}

func TestVerifiedReadsTheWriteBack(t *testing.T) {
	store := newFakeStore(map[string]string{registryPath: bareRegistry})
	got, err := app.New(store).PropagateVerified(request(&fakeContract{text: contractText}))
	if err != nil || got != app.Written {
		t.Fatalf("PropagateVerified = %v, %v, want Written", got, err)
	}
	if want := []string{"read " + registryPath, "write " + registryPath, "read " + registryPath}; strings.Join(store.log, "|") != strings.Join(want, "|") {
		t.Errorf("log %q, want %q", store.log, want)
	}
}

// kinds of a scripted read, for the table below.
var (
	gone  = notFound(registryPath)
	empty = text("")
	valid = text(bareRegistry)
	other = text(foreign)
)

// A sequence is the answers of the reads in order: the first is the read of the first attempt,
// and a read-back is the read after a write. Where the script ends the files are read.
func TestVerifiedWeighsTheEvidenceOfEveryAttempt(t *testing.T) {
	const attempts = app.MaxAttempts
	var (
		emptyErr        *app.EmptyRegistryError
		inconsistentErr *app.InconsistentRegistryError
		unverifiedErr   *app.UnverifiedWriteError
		lostErr         *app.LostWriteError
	)
	for _, c := range []struct {
		name   string
		script []answer
		want   app.Outcome
		err    any // a pointer to the error type wanted, or nil for success
		reads  int
	}{
		{"absent on every attempt", []answer{gone, gone, gone}, app.Absent, nil, 3},
		{"absent, then present: the second attempt writes", []answer{gone}, app.Written, nil, 0},
		{"empty on every attempt", []answer{empty, empty, empty}, 0, &emptyErr, 3},
		{"empty, then present", []answer{empty}, app.Written, nil, 0},
		{"empty twice, then present", []answer{empty, empty}, app.Written, nil, 0},
		{"absent, then empty twice", []answer{gone, empty, empty}, 0, &inconsistentErr, 3},
		{"empty, then absent twice", []answer{empty, gone, gone}, 0, &inconsistentErr, 3},
		{"empty, absent, empty", []answer{empty, gone, empty}, 0, &inconsistentErr, 3},
		{"absent twice, then empty", []answer{gone, gone, empty}, 0, &inconsistentErr, 3},
		{"empty twice, then absent", []answer{empty, empty, gone}, 0, &inconsistentErr, 3},
		{"a lost write, then absent twice", []answer{valid, other, gone, gone}, 0, &inconsistentErr, 4},
		{"a lost write, then empty twice", []answer{valid, other, empty, empty}, 0, &inconsistentErr, 4},
		{"a lost write, then empty, then absent", []answer{valid, other, empty, gone}, 0, &inconsistentErr, 4},
		{"absent, then two lost writes", []answer{gone, valid, other, valid, other}, 0, &lostErr, 5},
		{"a lost write every time", []answer{valid, other, valid, other, valid, other}, 0, &lostErr, 6},
		{"the read-back fails every time", []answer{valid, fails("io"), valid, fails("io"), valid, fails("io")}, 0, &unverifiedErr, 6},
		{"the registry is gone at every read-back", []answer{valid, gone, valid, gone, valid, gone}, 0, &unverifiedErr, 6},
		{"the read-back fails once", []answer{valid, fails("io")}, app.Unchanged, nil, 0},
		{"the read-back differs once", []answer{valid, other}, app.Unchanged, nil, 0},
	} {
		store := newFakeStore(map[string]string{registryPath: bareRegistry})
		store.script = c.script
		source := &fakeContract{text: contractText}
		got, err := app.New(store).PropagateVerified(request(source))
		if c.err == nil {
			if err != nil || got != c.want {
				t.Errorf("%s: PropagateVerified = %v, %v, want %v", c.name, got, err, c.want)
			}
			continue
		}
		if err == nil {
			t.Errorf("%s: PropagateVerified = %v, nil, want an error", c.name, got)
			continue
		}
		if !errors.As(err, c.err) {
			t.Errorf("%s: error %T %q, want %T", c.name, err, err, c.err)
		}
		if n := store.count("read"); n != c.reads {
			t.Errorf("%s: %d reads, want %d (log %q)", c.name, n, c.reads, store.log)
		}
		if source.reads > attempts {
			t.Errorf("%s: the contract was read %d times, more than %d attempts", c.name, source.reads, attempts)
		}
	}
}

func TestVerifiedErrorsCarryWhatTheCommandSays(t *testing.T) {
	read := newFakeStore(nil)
	read.script = []answer{valid, fails("input/output error"), valid, fails("input/output error"), valid, fails("input/output error")}
	_, err := app.New(read).PropagateVerified(request(&fakeContract{text: contractText}))
	var unverified *app.UnverifiedWriteError
	if !errors.As(err, &unverified) || unverified.Path != registryPath || unverified.Attempts != app.MaxAttempts ||
		unverified.Err == nil || !strings.Contains(unverified.Err.Error(), "input/output error") {
		t.Fatalf("error %#v, want an UnverifiedWriteError for %s after %d attempts holding the read-back's error", err, registryPath, app.MaxAttempts)
	}

	lost := newFakeStore(map[string]string{registryPath: bareRegistry})
	for n := 1; n <= app.MaxAttempts; n++ {
		lost.clobber[n] = foreign
	}
	_, err = app.New(lost).PropagateVerified(request(&fakeContract{text: contractText}))
	var lostErr *app.LostWriteError
	if !errors.As(err, &lostErr) || lostErr.Path != registryPath || lostErr.Attempts != app.MaxAttempts {
		t.Fatalf("error %#v, want a LostWriteError for %s after %d attempts", err, registryPath, app.MaxAttempts)
	}

	empty := newFakeStore(map[string]string{registryPath: ""})
	_, err = app.New(empty).PropagateVerified(request(&fakeContract{text: contractText}))
	var emptyErr *app.EmptyRegistryError
	if !errors.As(err, &emptyErr) || emptyErr.Path != registryPath || emptyErr.Attempts != app.MaxAttempts {
		t.Fatalf("error %#v, want an EmptyRegistryError for %s after %d attempts", err, registryPath, app.MaxAttempts)
	}
}

func TestVerifiedWritesAgainOnWhatTheForeignWriterLeft(t *testing.T) {
	store := newFakeStore(map[string]string{registryPath: bareRegistry})
	store.clobber[1] = foreign
	got, err := app.New(store).PropagateVerified(request(&fakeContract{text: contractText}))
	if err != nil || got != app.Written {
		t.Fatalf("PropagateVerified = %v, %v, want Written", got, err)
	}
	if store.writes != 2 {
		t.Errorf("%d writes, want 2 (the first was lost)", store.writes)
	}
	if !strings.Contains(store.files[registryPath], "regenerated by another tool") || !strings.Contains(store.files[registryPath], "minimalism-contract-scope") {
		t.Errorf("the second write did not go onto what the foreign writer left: %q", store.files[registryPath])
	}
}

func TestVerifiedAcceptsAForeignWriterThatKeptTheBlock(t *testing.T) {
	store := newFakeStore(map[string]string{registryPath: bareRegistry})
	store.clobber[1] = scoped(t) + "\nadded by another tool\n"
	got, err := app.New(store).PropagateVerified(request(&fakeContract{text: contractText}))
	if err != nil || got != app.Unchanged {
		t.Fatalf("PropagateVerified = %v, %v, want Unchanged on the second attempt", got, err)
	}
	if store.writes != 1 {
		t.Errorf("%d writes, want 1", store.writes)
	}
}

func TestVerifiedForwardsAHardFailureAtOnce(t *testing.T) {
	for _, c := range []struct {
		name   string
		source *fakeContract
		store  func() *fakeStore
		want   any
	}{
		{"a contract that cannot be read", &fakeContract{err: errors.New("denied")}, func() *fakeStore { return newFakeStore(nil) }, new(*app.ContractReadError)},
		{"a contract that does not parse", &fakeContract{text: "nothing"}, func() *fakeStore { return newFakeStore(nil) }, new(*app.ContractParseError)},
		{"a registry that cannot be read", &fakeContract{text: contractText}, func() *fakeStore {
			s := newFakeStore(nil)
			s.script = []answer{fails("denied")}
			return s
		}, new(*app.RegistryReadError)},
		{"a registry that cannot be written", &fakeContract{text: contractText}, func() *fakeStore {
			s := newFakeStore(map[string]string{registryPath: bareRegistry})
			s.failOn[1] = errors.New("full")
			return s
		}, new(*app.RegistryWriteError)},
	} {
		store := c.store()
		_, err := app.New(store).PropagateVerified(request(c.source))
		if err == nil || !errors.As(err, c.want) {
			t.Errorf("%s: error %T %v, want %T", c.name, err, err, c.want)
		}
		if c.source.reads != 1 {
			t.Errorf("%s: the contract was read %d times, want 1 (no retry)", c.name, c.source.reads)
		}
	}
}

func TestVerifiedForwardsAHardFailureOfALaterAttempt(t *testing.T) {
	store := newFakeStore(nil)
	store.script = []answer{empty, fails("denied")}
	_, err := app.New(store).PropagateVerified(request(&fakeContract{text: contractText}))
	var readErr *app.RegistryReadError
	if !errors.As(err, &readErr) {
		t.Fatalf("error %T %v, want a RegistryReadError from the second attempt", err, err)
	}
	if store.count("read") != 2 {
		t.Errorf("%d reads, want 2", store.count("read"))
	}
}

func TestVerifiedDoesNotRetryARegistryThatIsRequired(t *testing.T) {
	store := newFakeStore(nil)
	req := request(&fakeContract{text: contractText})
	req.RequireRegistry = true
	_, err := app.New(store).PropagateVerified(req)
	var required *app.RegistryRequiredError
	if !errors.As(err, &required) {
		t.Fatalf("error %T %v, want a RegistryRequiredError", err, err)
	}
	if store.count("read") != 1 {
		t.Errorf("%d reads, want 1: an explicit requirement fails fast", store.count("read"))
	}
}
